# Generated by Django 4.2.20 on 2025-05-10 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculocredito',
            name='economia_carbono',
            field=models.FloatField(blank=True, help_text='Economia de carbono pela reciclagem (kg CO2)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='calculocredito',
            name='emissao_carbono_reciclagem',
            field=models.FloatField(blank=True, help_text='Emissão de carbono se reciclado (kg CO2)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
