# Generated by Django 4.2.20 on 2025-05-10 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_calculocredito_economia_carbono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculocredito',
            name='emissao_carbono_atual',
            field=models.FloatField(blank=True, help_text='Emissão de carbono do método atual de descarte (kg CO2)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
